### ISSUE TITLE
Setup Kanban Board.

### ISSUE THREAD

**Issue by mailsg** [mailsg/React-Capstone-Space-Travellers-Hub#29]
Hi,

The Project Repository Link : https://github.com/mailsg/React-Capstone-Space-Travellers-Hub
The Project Kanban Board Setup Link : https://github.com/mailsg/React-Capstone-Space-Travellers-Hub/projects/1

Student A : @techmoves 
Student B : @mailsg 

Thanks.

**Comment by Davidosky007** [comment]
Hi @mailsg @techmoves 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Link to kanban board works 👍 
* All team members info provided 👍 
* Cards evenly assigned 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
